### ISSUE TITLE
Ruby Variables

### ISSUE THREAD

**Issue by ben-ole** [markbates/coffeebeans#4]
So how to use then my controllers instance variables? 

_show.js.coffee_

```
alert @search
```

Somewhat like this doesn't work for me. Is it possible at all?

Thanks, Benjamin

**Comment by markbates** [comment]
Use ERB:

```
alert "<%= @search %>"

```

**Comment by ben-ole** [comment]
Oh I tried but I forgot the quotes. Thanks a lot!

2011/7/14 markbates <
reply@reply.github.com>
