### ISSUE TITLE
Coffeebeans & ERB

### ISSUE THREAD

**Issue by moiristo** [markbates/coffeebeans#5]
In Rails 3.1 final, when creating a file with both the .coffee and .erb extension doesn't work for me (in any order). The result is that the view is not recognized as a proper respond format and therefore the HTML view of the action is rendered instead (or a missing template error is thrown if no other format is available).

**Comment by moiristo** [comment]
Might be that I misunderstood and that ERB is just available in the coffeescript code, but when I only use the .coffee extension I get an ExecJS compile error.

**Comment by markbates** [comment]
ERB is already available. Just name your file foo.js.coffee and it should work.
