### ISSUE TITLE
escaping too much?

### ISSUE THREAD

**Issue by fringd** [markbates/coffeebeans#6]
for some reason this:

``` javascript
$('div.input table tr.attachment-row .remove_row').click()
<% if @project.portfolio %>
portfolio_id = '<%=escape_javascript @project.portfolio_id.to_s %>'
portfolio_name = '<%=escape_javascript @project.portfolio.name %>'
portfolio = $('#project_portfolio_id')
option = portfolio.find('option[value='+portfolio_id+']')
if option.length is 0
  optionhtml = '<option value='+portfolio_id+'>'+portfolio_name+'</option>'
  portfolio.find('option').last().before(optionhtml)
portfolio.val(portfolio_id)
<% end %>
```

is rendering as this:

``` javascript
/*snip*/

if (option.length === 0) {
  optionhtml = '&lt;option value=' + portfolio_id + '&gt;' + portfolio_name + '&lt;/option&gt;';
  portfolio.find('option').last().before(optionhtml);
}

/*snip*/
```

not the problematic &lt;, &gt; also if i use the rubyish string evaluations ("foo#{var}bar...") it escapes my double quotes and i end up with invalid syntax... why!? is this coffee beans' fault?

**Comment by fringd** [comment]
so ok, the issue i was having was a result of including coffeescript as a partial without escaping it. everything above was being html_escaped because it was being included below

``` erb
<%= render :partial => 'filefields'%>
```

changing it to the following fixed the problem:

``` erb
<%=raw render :partial => 'filefields'%>
```

perhaps the problem is that the containing file wasn't a .js.coffee, but a .js.erb it seems that the string returned by coffeebeans is not html_safe, so it might be easy to fix that in the gem.

**Comment by markbates** [comment]
I'll happily release a new version with html safe string if you want to send a pull request.

**Comment by fringd** [comment]
added a pull request
